name: Deploy Frontend Feedback Site

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: |
            cd feedback
            npm ci

      - name: Build React app with Vite
        run: |
            cd feedback
            npm run build 

      - name: Upload build files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: feedback/dist 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.x

      - name: Initialize Terraform
        run: |
          cd infra  
          terraform init

      - name: Download the build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: infra/dist 

      - name: Run Terraform Plan
        run: |
          cd infra  
          terraform plan
